### ISSUE TITLE
Lazy Loading UITableView sometimes shows previously queued image

### ISSUE THREAD

**Issue by inturbidus** [nicklockwood/AsyncImageView#13]
I have a UITableView that is using your AsyncImageView (great stuff btw).  If I scroll up and down, I often get a different image than was requested.  It seems like it may be a problem with dequeing the proper cell.  I usually have to scroll up and down a couple of times.

It seems like it comes when it should be showing default.

**Comment by iHiD** [comment]
@nicklockwood: I'm seeing the same issue as @jabbarfast 

I have the following code (which I've checked gets called):
```
    override func prepareForReuse() {
        super.prepareForReuse()
        
        AsyncImageLoader.sharedLoader().cancelLoadingImagesForTarget(imageView)
        self.imageView.imageURL = nil
    }
```

However, I still see previous images before the new ones load. I've tried that code in the cell and in the view. I am using a `CollectionView`, not a `TableView` so I wonder if that might be the difference?

Could you provide any more ideas for me to explore please?

Thanks in advance for your help and for creating an awesome library :)

**Comment by cenck09** [comment]
I can't speak for a collectionView, but for a tableview:

When creating a new cell I also create the imageView with a frame:

            asyncImageView = [[AsyncImageView alloc] initWithFrame:CGRectMake(4, 2, iPhoneCellHeight-4  , iPhoneCellHeight-4)];


Give it a tag:
        asyncImageView.tag = 10;

Then I pass that to a basic imageView and add as subview to cell:

        UIImageView *imageViewForCell = asyncImageView;
       imageViewForCell.frame = asyncImageView.frame;    
        imageViewForCell.contentMode = UIViewContentModeScaleAspectFit;   
       [cell.contentView addSubview:imageViewForCell];


Then after you're done making the new cell, or if you're reusing a cell, but still in cellForRowAtIndex:


 AsyncImageView *imageView = (AsyncImageView *)[cell viewWithTag:10];
    
    //cancel loading previous image for cell, as to not clog things up when a user scrolls fast
    [[AsyncImageLoader sharedLoader] cancelLoadingImagesForTarget:imageView];
 
  // Then I clear out the image by setting it to nil
   imageView.image = nil;

    // Tell the imageView to load the new image
    imageView.imageURL = [galleryData getURLforImageFileForArtworkWithID:[artworkObject objectId]];

 
 Hope this helps because I had the same problem you're describing, just with a tableView
